
site_name: DoD Prohibited Ingredients
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.instant
    - toc.integrate
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - content.tabs.link
    - content.tabs.sticky
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - content.code.expand
    - content.code.fold
    - content.code.highlight
    - content.code.line_numbers
    - content.code.language
    - content.code.title
    - content.code.caption
    - content.code.toolbar
    - content.code.wrap
    - content.code.unfold
    - content.code.unselect
    - content.code.unfold_all
    - content.code.unselect_all
    - content.code.unfold_selected
    - content.code.unfold_all_selected
    - content.code.unfold_all_unselected
    - content.code.unfold_selected_all
    - content.code.unfold_selected_unselected
    - content.code.unfold_unselected_all
    - content.code.unfold_unselected_selected
    - content.code.unfold_unselected_unselected
    - content.code.unfold_selected_selected
    - content.code.unfold_selected_unselected_selected
    - content.code.unfold_selected_unselected_unselected
    - content.code.unfold_unselected_selected_selected
    - content.code.unfold_unselected_selected_unselected
    - content.code.unfold_unselected_unselected_selected
    - content.code.unfold_unselected_unselected_unselected
    - content.code.unfold_selected_selected_selected
    - content.code.unfold_selected_selected_unselected
    - content.code.unfold_selected_unselected_selected_selected
    - content.code.unfold_selected_unselected_selected_unselected
    - content.code.unfold_selected_unselected_unselected_selected
    - content.code.unfold_selected_unselected_unselected_unselected
    - content.code.unfold_unselected_selected_selected_selected
    - content.code.unfold_unselected_selected_selected_unselected
    - content.code.unfold_unselected_selected_unselected_selected
    - content.code.unfold_unselected_selected_unselected_unselected
    - content.code.unfold_unselected_unselected_selected_selected
    - content.code.unfold_unselected_unselected_selected_unselected
    - content.code.unfold_unselected_unselected_unselected_selected
    - content.code.unfold_unselected_unselected_unselected_unselected
    - content.code.unfold_selected_selected_selected_selected
    - content.code.unfold_selected_selected_selected_unselected
    - content.code.unfold_selected_selected_unselected_selected
    - content.code.unfold_selected_selected_unselected_unselected
    - content.code.unfold_selected_unselected_selected_selected_selected
    - content.code.unfold_selected_unselected_selected_selected_unselected
    - content.code.unfold_selected_unselected_selected_unselected_selected
    - content.code.unfold_selected_unselected_selected_unselected_unselected
    - content.code.unfold_selected_unselected_unselected_selected_selected
    - content.code.unfold_selected_unselected_unselected_selected_unselected
    - content.code.unfold_selected_unselected_unselected_unselected_selected
    - content.code.unfold_selected_unselected_unselected_unselected_unselected
    - content.code.unfold_unselected_selected_selected_selected_selected
    - content.code.unfold_unselected_selected_selected_selected_unselected
    - content.code.unfold_unselected_selected_selected_unselected_selected
    - content.code.unfold_unselected_selected_selected_unselected_unselected
    - content.code.unfold_unselected_selected_unselected_selected_selected
    - content.code.unfold_unselected_selected_unselected_selected_unselected
    - content.code.unfold_unselected_selected_unselected_unselected_selected
    - content.code.unfold_unselected_selected_unselected_unselected_unselected
    - content.code.unfold_unselected_unselected_selected_selected_selected
    - content.code.unfold_unselected_unselected_selected_selected_unselected
    - content.code.unfold_unselected_unselected_selected_unselected_selected
    - content.code.unfold_unselected_unselected_selected_unselected_unselected
    - content.code.unfold_unselected_unselected_unselected_selected_selected
    - content.code.unfold_unselected_unselected_unselected_selected_unselected
    - content.code.unfold_unselected_unselected_unselected_unselected_selected
    - content.code.unfold_unselected_unselected_unselected_unselected_unselected
    - content.code.unfold_selected_selected_selected_selected_selected
    - content.code.unfold_selected_selected_selected_selected_unselected
    - content.code.unfold_selected_selected_selected_unselected_selected
    - content.code.unfold_selected_selected_selected_unselected_unselected
    - content.code.unfold_selected_selected_unselected_selected_selected
    - content.code.unfold_selected_selected_unselected_selected_unselected
    - content.code.unfold_selected_selected_unselected_unselected_selected
    - content.code.unfold_selected_selected_unselected_unselected_unselected
    - content.code.unfold_selected_unselected_selected_selected_selected_selected
    - content.code.unfold_selected_unselected_selected_selected_selected_unselected
    - content.code.unfold_selected_unselected_selected_selected_unselected_selected
    - content.code.unfold_selected_unselected_selected_selected_unselected_unselected
    - content.code.unfold_selected_unselected_selected_unselected_selected_selected
    - content.code.unfold_selected_unselected_selected_unselected_selected_unselected
    - content.code.unfold_selected_unselected_selected_unselected_unselected_selected
    - content.code.unfold_selected_unselected_selected_unselected_unselected_unselected
    - content.code.unfold_selected_unselected_unselected_selected_selected_selected
    - content.code.unfold_selected_unselected_unselected_selected_selected_unselected
    - content.code.unfold_selected_unselected_unselected_selected_unselected_selected
    - content.code.unfold_selected_unselected_unselected_selected_unselected_unselected
    - content.code.unfold_selected_unselected_unselected_unselected_selected_selected
    - content.code.unfold_selected_unselected_unselected_unselected_selected_unselected
    - content.code.unfold_selected_unselected_unselected_unselected_unselected_selected
    - content.code.unfold_selected_unselected_unselected_unselected_unselected_unselected
    - content.code.unfold_unselected_selected_selected_selected_selected_selected
    - content.code.unfold_unselected_selected_selected_selected_selected_unselected
    - content.code.unfold_unselected_selected_selected_selected_unselected_selected
    - content.code.unfold_unselected_selected_selected_selected_unselected_unselected
    - content.code.unfold_unselected_selected_selected_unselected_selected_selected
    - content.code.unfold_unselected_selected_selected_unselected_selected_unselected
    - content.code.unfold_unselected_selected_selected_unselected_unselected_selected
    - content.code.unfold_unselected_selected_selected_unselected_unselected_unselected
    - content.code.unfold_unselected_selected_unselected_selected_selected_selected
    - content.code.unfold_unselected_selected_unselected_selected_selected_unselected
    - content.code.unfold_unselected_selected_unselected_selected_unselected_selected
    - content.code.unfold_unselected_selected_unselected_selected_unselected_unselected
    - content.code.unfold_unselected_selected_unselected_unselected_selected_selected
    - content.code.unfold_unselected_selected_unselected_unselected_selected_unselected
    - content.code.unfold_unselected_selected_unselected_unselected_unselected_selected
    - content.code.unfold_unselected_selected_unselected_unselected_unselected_unselected
    - content.code.unfold_unselected_unselected_selected_selected_selected_selected
    - content.code.unfold_unselected_unselected_selected_selected_selected_unselected
    - content.code.unfold_unselected_unselected_selected_selected_unselected_selected
    - content.code.unfold_unselected_unselected_selected_selected_unselected_unselected
    - content.code.unfold_unselected_unselected_selected_unselected_selected_selected
    - content.code.unfold_unselected_unselected_selected_unselected_selected_unselected
    - content.code.unfold_unselected_unselected_selected_unselected_unselected_selected
    - content.code.unfold_unselected_unselected_selected_unselected_unselected_unselected
    - content.code.unfold_unselected_unselected_unselected_selected_selected_selected
    - content.code.unfold_unselected_unselected_unselected_selected_selected_unselected
    - content.code.unfold_unselected_unselected_unselected_selected_unselected_selected
    - content.code.unfold_unselected_unselected_unselected_selected_unselected_unselected
    - content.code.unfold_unselected_unselected_unselected_unselected_selected_selected
    - content.code.unfold_unselected_unselected_unselected_unselected_selected_unselected
    - content.code.unfold_unselected_unselected_unselected_unselected_unselected_selected
    - content.code.unfold_unselected_unselected_unselected_unselected_unselected_unselected
plugins:
  - search
  - awesome-pages
  - literate-nav
  - glightbox
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gooosetavo/dod-prohibited
nav:
  - Home: index.md
  - Substances:
      - substances/index.md
      # Individual substance pages will be auto-generated in substances/
